# Generated by Django 4.0.6 on 2025-09-03 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='fisrt_name',
            new_name='first_name',
        ),
    ]
